INSERT INTO app_settings (setting_key, setting_value, setting_meaning) VALUES
  ('program_name','serBAR','Nome del programma'),
  ('program_author','Michele Olimpi','Autore del programma'),
  ('program_version','V00.20260913','Versione del programma'),
  ('program_whatsNewSplash','0','Mostra novita al login'),
  ('login_info1','ACLI Grassina','Messaggio login riga 1'),
  ('login_info2','Gestione turni','Messaggio login riga 2'),
  ('consultation_directory_enabled','1','Abilita rubrica consultazione'),
  ('consultation_interface_enabled','1','Abilita area consultazione'),
  ('consultation_notifications_enabled','1','Abilita notifiche consultazione'),
  ('public_interface_enabled','1','Abilita interfaccia pubblica'),
  ('public_interface_passkey','defaultPasskey','Chiave accesso pubblico'),
  ('public_interface_refresh_seconds','60','Aggiornamento pubblico secondi'),
  ('print_forcedPageBreak','0','Interruzione pagina stampa'),
  ('print_forcedPageBreakHeader','0','Interruzione intestazione stampa'),
  ('print_tableTitle','SERVIZIO BAR','Titolo tabella stampa'),
  ('print_tableMoonPhases','0','Mostra fasi lunari'),
  ('email_sending_enabled','0','Abilita invio email'),
  ('smtp_auth_enabled','1','Abilita autenticazione SMTP'),
  ('smtp_auth_type','tls','Tipo autenticazione SMTP'),
  ('smtp_password','','Password SMTP'),
  ('smtp_port','587','Porta SMTP'),
  ('smtp_server','example.smtp.local','Server SMTP'),
  ('smtp_username','','Nome utente SMTP')
ON DUPLICATE KEY UPDATE setting_meaning = VALUES(setting_meaning);
