INSERT IGNORE INTO app_settings (setting_key, setting_value) VALUES
  ('program_name','serBAR'),
  ('program_author','Michele Olimpi'),
  ('program_version','V00.00'),
  ('login_info1','ACLI Grassina'),
  ('login_info2','Gestione turni'),
  ('consultation_directory_enabled','1'),
  ('consultation_interface_enabled','1'),
  ('consultation_notifications_enabled','1'),
  ('public_interface_enabled','1'),
  ('public_interface_passkey',''),
	('smtp_auth_enabled','1'),
  ('smtp_auth_type','tls'),
  ('smtp_password',''),
  ('smtp_port','587'),
  ('smtp_server',''),
  ('smtp_username','');
