INSERT IGNORE INTO app_settings (setting_key, setting_value) VALUES
  ('program_name','serBAR'),
  ('program_author','Michele Olimpi'),
  ('program_version','V00.20260913'),
  ('program_whatsNewSplash','0',''),
  ('login_info1','ACLI Grassina',''),
  ('login_info2','Gestione turni',''),
  ('consultation_directory_enabled','1',''),
  ('consultation_interface_enabled','1',''),
  ('consultation_notifications_enabled','1',''),
  ('public_interface_enabled','1','Interfaccia pubblica attiva'),
  ('public_interface_passkey','defaultPasskey',''),
  ('public_interface_refresh_seconds','60','Tempo aggiornamento interfaccia pubblica'),
  ('print_forcedPageBreak','0'),'',
  ('print_forcedPageBreakHeader','0',''),
  ('print_tableTitle','SERVIZIO BAR','Titolo statico cartellone'),
  ('print_tableMoonPhases','0','Fasi lunari su cartellone (non attivo)'),
  ('email_sending_enabled','0',''),
  ('smtp_auth_enabled','1',''),
  ('smtp_auth_type','tls',''),
  ('smtp_password','',''),
  ('smtp_port','587',''),
  ('smtp_server','example.smtp.local',''),
  ('smtp_username','','');
